version: 2
jobs:
  build:
    docker:
      - image: node:latest
    working_directory: /paybase
    steps:
      - checkout
      - run:
          name: dependencies
          command: npm install
      - run:
          name: test
          command: npm test
      - deploy:
          name: publish package
          command: bash ./ci/publish.sh
